services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
